### ISSUE TITLE
You need a read me

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/react-native-weather#2]
Your project needs a read me. Provide information under headings like these: 

- Title 
- Overview
- Getting started
- Installation 
- Todo

Include a description of the project and an image. Provide a rationale for creating the project. 

It might be a good idea to keep the React Native guide in the existing read me but, the information here either goes after your read me or should be linked to from the main read me.

**Comment by Jeffchiucp** [comment]
updated the ReadMe with the following information:

Title
Overview
Getting started
Installation
Todo
