### ISSUE TITLE
Not working? 

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/react-native-weather#4]
Doesn't seem to be working? It's always Oct 4 72˚...

This looks like mostly what I gave out. You should try and do something more with this. 

Looks like you are not calling `findWeather()` at any point, or doing anything with the weather data once it is loaded...

**Comment by Jeffchiucp** [comment]
I refactored the DayTemp and implement different classes

**Comment by Jeffchiucp** [comment]
this is closed!
