### ISSUE TITLE
class DayTemp

### ISSUE THREAD

**Issue by soggybag** [Jeffchiucp/react-native-weather#5]
`class DayTemp` is probably better as a function based component. It doesn't have any state to keep track of.

**Comment by Jeffchiucp** [comment]
working progress on this enhancement

**Comment by Jeffchiucp** [comment]
implemented the changes to DayTemp class

**Comment by Jeffchiucp** [comment]
and it works with the correct temperatures

**Comment by Jeffchiucp** [comment]
this is closed!
